---
name: Quick Checker

on:
  push:
    branches: [ 'ci-*' ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 500
      - name: Environment
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "HEAD: $(git rev-list -1 HEAD)"
          if test -n "$GITHUB_BASE_REF"; then
            BASEB=$(git rev-list -1 HEAD^1)
            HEADB=$(git rev-list -1 HEAD^2)
          else
            git fetch --no-tags --no-recurse-submodules --depth=500 origin main
            BASEB=origin/main
            HEADB=HEAD
          fi
          echo "BASEB: $BASEB"
          echo "HEADB: $HEADB"
          echo "BASEB=$BASEB" >> "$GITHUB_ENV"
          echo "HEADB=$HEADB" >> "$GITHUB_ENV"
      - name: Deep enough fetch?
        run: git merge-base ${{env.BASEB}} ${{env.HEADB}}
      - name: Check Email
        run:  sh ./tools/build/check-email.sh ${{env.BASEB}}..${{env.HEADB}}
      - name: Check Style
        run:  ./tools/build/checkstyle9.pl -color=always ${{env.BASEB}}..${{env.HEADB}}
