name: Style Checker

on:
  push:
    branches: [ main, 'stable/13', 'stable/14' ]
  pull_request: # maybe pull_request_target
    branches: [ main ]
#    types: [ opened, reopened, edited ]

permissions:
  contents: read

jobs:
  build:
    name: Style Checker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install packages
        run: |
          sudo apt-get update --quiet || true
          sudo apt-get -yq --no-install-suggests --no-install-recommends install perl
      - name: Run checker
        run: |
          sha=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          tools/build/checkstyle9.pl ${sha}..${{ github.event.pull_request.head.sha }}
